### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cali0028** [ilcato/homebridge-ifttt#1]
Not sure where else to put this but I thought I ask here. 

With this plug-in do you still need to use the hashtag command when using siri? 

thanks

**Comment by ilcato** [comment]
not sure to understand the question ...

**Comment by cali0028** [comment]
So today if we want d to use ifttt via Siri we would say "Siri send a message to (ifttt number) #garahe" for example to open a garage door. 

So I was wondering if it's the same case.

**Comment by ilcato** [comment]
Ok, with this solution you can say "turn on garageopen " to activate a corresponding trigger on the Maker channel. You can then create a recipe to call the outbound garage channel

**Comment by cali0028** [comment]
Hmmm okay now I've to plan and figure out how to do this on the smartthings hub
