### ISSUE TITLE
Is someone working on a method to send a value back to IFTTT?

### ISSUE THREAD

**Issue by JOyo246** [ilcato/homebridge-ifttt#10]

**Comment by JangoBritt** [comment]
I don't think that would work with the Maker Channel, as the Maker channel only receives a single trigger command, and not a value to go with it.

**Comment by ilcato** [comment]
It seems that parameters are no more available to the Maker Channel.

**Comment by ilcato** [comment]
@JOyo246, @JangoBritt, it is still an available feature.
I try to implement to allow a dimmer style accessory.

**Comment by ilcato** [comment]
@JOyo246, what's your use case?

**Comment by JOyo246** [comment]
I want to be able to control my Aros air conditioner from HomeKit. Since the wink aros doesn't work with aros, I'm currently using IFTTT with the aros channel at 8 different degree intervals. So my home app has 8 different aros switches all with different degree values to be sent to different applets. So to set my air conditioner to 72, I say, hey Siri, turn on aros 72. All though this works, it would be better to be able to have a set value stored somewheres in IFTTT, then when I set it from my phone, I can use any number that would change it.

**Comment by ilcato** [comment]
So the parameter is a temperature value, is it right? If I map it to a the Temperature characteristic of a Thermostat HomeKit accessory and send any variation of the target temperature as a Maker request with a temperature parameter as a value this should be ok for you. You will be able to say "set temperature of aros to 72".

**Comment by JOyo246** [comment]
I think that's correct. The best solution would be to fix the wink-homebridge aros accessory.

**Comment by burkybang** [comment]
@JOyo246 I just submitted a PR that does this.

https://github.com/ilcato/homebridge-ifttt/pull/39

**Comment by JOyo246** [comment]
@burkybang thanks! However the home bridge-wink3 accessory has been working great for me!

**Comment by burkybang** [comment]
@JOyo246 Cool, hopefully others who don't use Wink can get use out of this.

**Comment by ilcato** [comment]
Published in version 0.4.0
