### ISSUE TITLE
Persist For TriggerOn function request

### ISSUE THREAD

**Issue by jacobwtyler** [ilcato/homebridge-ifttt#11]
Is there anyway I could modify the config file to add the ability to remember the state of my IFTTT toggle switches in the Home app? It reverts to Off everytime the Home app refreshes the devices. I'm using TriggerOn and TriggerOff for these switches and I understand it could get out of sync but it won't be an issue for me as I only control these IFTTT commands through Homebridge. Thanks for all the work.

**Comment by abataille** [comment]
To accomplish this, I suggest the following small changes to the index.js

at the end of index.js insert a line in function IFTTTAccessory so that it reads

function IFTTTAccessory(services) {
    this.onoffstate = false;
    this.services = services;
}

in bindCharacteristisEvents: (line  152 change else if ... else to
else if (value == 0)
	{trigger = service.controlService.triggerOff;
          this.onoffstate = false;
           }
else {
	trigger = service.controlService.triggerOn;
          this.onoffstate = true;
           }

and last in characteristic.on change the callback to
	callback(undefined, this.onoffstate);
                   }.bind(this) );

That' s it.

**Comment by ilcato** [comment]
Did you test it?

**Comment by abataille** [comment]
I did and it is running in my homebridge installation.
Practically it adds an variable onoffstate to the accessory. Initially it is false and stays false if you defined a push button. In all other cases the variable is set with triggering/off.
The .get function just returns the variable.
That's it.

**Comment by ilcato** [comment]
Can you make a pull request?

**Comment by abataille** [comment]
Theoretically yes, but I am for the next two weeks on iPad only.

**Comment by ilcato** [comment]
Committed a new version.
@abataille, I changed the on('get') event in order to manage also the push button case.
@jacobwtyler, are you able to test it?

**Comment by abataille** [comment]
It works in my installation.
