### ISSUE TITLE
Send values with the button

### ISSUE THREAD

**Issue by poudenes** [ilcato/homebridge-ifttt#15]
Hi There,

is it possible to send some information with the trigger?

{{Value1}}, {{Value2}}, {{Value3}}, {{OccurredAt}}

The last one will filled in by IFTTT itself, but if you send send information that fill the Value1, Value2 and Value3 then you only have to create 1 MAKER and use it for multiple actions.

**Comment by poudenes** [comment]
https://maker.ifttt.com/trigger/Huisleeg/with/key/API KEY/?value1=test1&value2=test2&value3=test3

This is working. but now want it into a plugin :)

**Comment by deadlyknapsack** [comment]
This is flagged as an enhancement, but I feel like there is nothing happening in terms of development on this plugin. Is that true? I would really like to send values as well.

**Comment by burkybang** [comment]
I just submitted a pull request adding this feature: https://github.com/ilcato/homebridge-ifttt/pull/39

**Comment by ilcato** [comment]
Published in version 0.4.0
