### ISSUE TITLE
Switch it turning itself off even though I have a triggerOn and triggerOff set. 

### ISSUE THREAD

**Issue by webpablo** [ilcato/homebridge-ifttt#19]
I have setup a switch that I want to remain either on or off and to send the opposite command when toggled. For some reason, the switch when enabled, automatically disables. If I am reading the documentation right, I feel like this should only be happening if I didn't define both?

**Comment by webpablo** [comment]
I was using the NPM version. After digging through closed issues I realize you addressed this very issue in the last update. Any chance of pushing to NPM for future users?

**Comment by ilcato** [comment]
done
