### ISSUE TITLE
IFTTT Switch actions

### ISSUE THREAD

**Issue by WilliamHF** [ilcato/homebridge-ifttt#2]
Hi,

Congrats for the great job with this module.

Just a remark, I am using the homebridge-ifttt for switches, and therefore I have to create two distinct accessories for switching on / switching off actions. (As currently, translated into any HomeKit app, both On and Off buttons will launch the same trigger).
Perhaps you could develop different types of accessories, keeping this push-button behavior, but also adding dual trigger (on/off) actions. 

Regards,
Will

**Comment by ilcato** [comment]
Ok, no problem in defining a different kind of accessory that maps to a Switch. Do you think that it is better to have two different Maker triggers for on and off status or to have the same trigger with a value parameter that transmit the status (on/off) ?

**Comment by WilliamHF** [comment]
Hi Ilcato, thanks for your quick answer.

I believe the maker channel on ifttt uses only the event name trigger for an action, and anyway the optional value parameters are not passed to the "then" channels that I use, so yes for now I think 2 different triggers would be my only option.
Much appreciated!

**Comment by ilcato** [comment]
Done in version 0.2.0.
@WilliamHF can you test it with your configuration?
You need to specify both "triggerOn" and "triggerOff" parameter and not "trigger" in order to obtain the bistable switch behavior.

**Comment by WilliamHF** [comment]
Hi ilcato,

Sorry for the late answer. Just updated and tried it, it works perfectly ! Brilliant ! "Turn/switch on" and "turn/switch off" commands seem indeed more natural now !

Thanks a lot,

**Comment by armins2k** [comment]
Hello,

first of all great work! I'm using the ifttt channel to arm and disarm my alarm system and it works perfectly. I can use scenes or siri commands, no problem.
But is it possible to make the On/Off switches to keep there current status? Right now if I use the On switch it always resets to Off again. Would be nice to see the switch in its On position when using one of the homekit apps.

Thanks for the assistence!!

**Comment by ilcato** [comment]
@armins2k: are you using a triggerOn/triggerOff couple of only a trigger parameter? In the first case the switch should remain in the status you set.

**Comment by armins2k** [comment]
I'm using triggerOn triggerOff and the triggers work fine. Only within apps like Elgato Eve, the On switch always resets to Off after activating it and refreshing.

Here is part of my config file:

...

, {
"platform": "IFTTT",
"name": "IFTTT",
"makerkey": "*****************",
"accessories": [{
"name": "Überwachung",
"buttons": [{
"caption": "Überwachung",
"triggerOn": "ÜberwachungOn",
"triggerOff": "ÜberwachungOff"
}]
}, {
"name": "Nachtüberwachung",
"buttons": [{
"caption": "Nachtüberwachung",
"triggerOn": "NachtüberwachungOn",
"triggerOff": "NachtüberwachungOff"
}]
}]
}]
}

I tried already uninstalling and reinstalling the plugin, but no change.

**Comment by ilcato** [comment]
Understood.
The problem is that when you refresh or when you enter the panel of a switch I have no way to understand what the status of the switch is: I cannot inquire IFTTT on this.
The only possible solution is to persist the status info in homebridge but it can easily became misaligned if you operate on the device without homebridge.

**Comment by armins2k** [comment]
Okay, thanks for the info! Makes sense.
So how can I achieve it that homebridge keeps the buttons status?

**Comment by ilcato** [comment]
The plugin must be extended with this functionality :-)

**Comment by armins2k** [comment]
I see I see, probably I'm not skilled enough for that. Any chance of seeing it implemented in a future version?

Thanks for the fast assistence!

**Comment by ilcato** [comment]
It's on my to do list ...

**Comment by dotdd** [comment]
+1 for this, gonna be super useful! Any news on when would it be available?

**Comment by jacobwtyler** [comment]
+1 for this. I'd love to have the status persist. I only us homebridge for this so alignment would be non issue. Thanks for all the work!!

**Comment by lwhuybrechts** [comment]
+1, this would make the plugin perfect to use from the homekit view in control centre in iOS 10. Anyway thanks for the awesome work so far 👍

**Comment by ilcato** [comment]
@armins2k, @lwhuybrechts, @dotdd 
can you test the latest commit to understand if it works?
I implemented the @abataille suggestion coming from #11.

**Comment by dotdd** [comment]
@ilcato How do I get the latest version? Do I install just like normally? npm install -g homebridge-ifttt

**Comment by ilcato** [comment]
I didn't published it on npm yet.
Just replace (after saving it) the index.js file on you installation with the latest one on GitHub and restart homebridge.

Andrea

**Comment by dotdd** [comment]
It seems to be working - tho, I have to switch and the status seems to affect both (even tho in reality only one action was taken). When I switch on my Living Room A/C, both switch are indicated as On but only Living Room one sent the action to IFTTT.

"platform": "IFTTT",
		"name": "IFTTT",
		"makerkey": "cTDiVgDTxWaIuxgZh8eb4E",
		"accessories": [{
			"name": "Living Room A/C",
			"buttons": [{
				"caption": "Living Room A/C",
				"triggerOn": "SLROn",
				"triggerOff": "SLROff"
			}]},{
			"name": "Bedroom A/C",
			"buttons": [{
				"caption": "Bedroom A/C",
				"triggerOn": "SBROn",
				"triggerOff": "SBROff"
			}]
		}]

**Comment by lwhuybrechts** [comment]
@ilcato tested and works perfectly! Since I have separate on/off actions in IFTTT instead of a toggle action I can press it twice when the switch gets out of sync. Btw, I only have one switch so cannot confirm the same problem as @dotdd.

@dotdd you have accidentally commented your makerkey :no_good_man: Make sure you reset it to a new key in case someone saw it. You can do this in IFTTT by clicking "Edit connection" on this page: https://ifttt.com/services/maker/settings.

**Comment by dotdd** [comment]
Thanks @lwhuybrechts it's already reset. Yeah, the only problem now is if multiple switches they will change the state together.

**Comment by ilcato** [comment]
@dotdd, I replicated your issue and trying to fix it.

**Comment by ilcato** [comment]
@dotdd, I think I fixed the bug. Can you test it before I'll publish the new version? Thanks

**Comment by dotdd** [comment]
@ilcato Happy new year. Sorry for the late. I just returned from my holiday and tested your updated file it works!
