### ISSUE TITLE
iOS 11 Beta 4 Not working

### ISSUE THREAD

**Issue by marcodesantis71** [ilcato/homebridge-ifttt#24]
Hi,

I just installed iOS 11 Beta 4 and now ifttt plugin not working.

No error on the logs of homrbidge. The Home App return "not responding" error.

Another iPhone with iOS 10 Works fine.

**Comment by deanlyoung** [comment]
@marcodesantis71 I believe this is an issue with Homebridge. A bug was likely introduced, which broke Homebridge's connection.
