### ISSUE TITLE
Adding persistence for Switch after Reboot / Restart

### ISSUE THREAD

**Issue by Nastras** [ilcato/homebridge-ifttt#26]
Hello,
is it possible that the status of the switch after a reboot exist?

I've uncovered this feature with this plugin and would like it for the IFTTT plugin as well.

https://github.com/nfarina/homebridge-dummy

https://github.com/nfarina/homebridge-dummy/pull/5

**Comment by ToddGreenfield** [comment]
@Nastras Give my fork a try and see if it works for you. My flight was canceled so I had some time today.
https://github.com/ToddGreenfield/homebridge-ifttt

If it works well we can do a PR to merge here. Again, I don't really use ifttt but I think this should work.

**Comment by Nastras** [comment]
That's great, thank you for your efforts. I'll test it when I'm at home and let you know.

**Comment by Nastras** [comment]
Hello, I usually wanted to let you know that it works. You can now make a pull request.

Thank you again!

**Comment by Nastras** [comment]
That was very fast. Thanks again to you @ToddGreenfield and you @ilcato !

**Comment by Nastras** [comment]
Apparently, I was happy too soon, just wanted to make the update and have found that no update is offered?

@ilcato Does the update still appear?

**Comment by ToddGreenfield** [comment]
Guessing NPM hasn’t been updated/published yet. Try uninstalling and reinstalling, that should grab the current code until an npm publish.

**Comment by ilcato** [comment]
Will update the mpm in a few hours. Need a pc.

**Comment by Nastras** [comment]
Great. Thank you !

**Comment by ilcato** [comment]
done

**Comment by Nastras** [comment]
👍👍👍
