### ISSUE TITLE
Delay Switch is not working

### ISSUE THREAD

**Issue by xMAIKx** [ilcato/homebridge-ifttt#29]
I want the switch in HomeKit to go off automatically after 5 seconds. Unfortunately, this does not work, no matter what time I set in the Config.
{
"name": "Wasserkocher Kueche",
"buttons": [{
"caption": "Wasserkocher",
"trigger": "Wasserkocher_on",
"delayOn": 5
}]
},

**Comment by rgerr** [comment]
Are you sure it is seconds, not minutes?
