### ISSUE TITLE
Setup question 

### ISSUE THREAD

**Issue by cali0028** [ilcato/homebridge-ifttt#3]
So I've installed the plug in but still trying to get my heads around how this supposed to work. 
- I've installed the plug in
- Here is my input on my config file 
      {
          "platform": "IFTTT",
          "name": "IFTTT",
          "makerkey": "My Key is here from IFTTT/Maker",
          "accessories": [
              {
                  "name": "Garage",
                  "buttons": [
                      {
                          "caption": "Open_Garage",
                          "triggerOn": "Open_Garage"
                      },
                      {
                          "caption": "Close_Garage",
                          "triggerOn": "Close_Garage"
                      }
- created the recipe in iFTTT 

Now how do I trigger it to open via siri? 

Sorry for the nobb question as I'm still learning this whole IFTTT.

**Comment by ilcato** [comment]
You can say something like this: "Activate Open_Garage".
In order to not confuse Siri it is better to assign a more unambiguous caption to the buttons.

**Comment by cali0028** [comment]
So if I had labeled it "Open Garage" rather than "Open_Garage", I should say "Activate Open Garage" Rather than "Activate Open_Garage"?

Also does the Code look okay, meaning the way I've written it? 

Thanks

**Comment by ilcato** [comment]
No, I suggested to not using words like Open or similar because it can confuse Siri.
The configuration code seems ok to me.

**Comment by cali0028** [comment]
Ah okay! Thank you! I'll give that a try tonight. Sorry this is IFTTT and maker is new to me.

**Comment by ilcato** [comment]
If you want to generate a trigger with a momentary switch you need to define in the config file only the parameter trigger associated to a button. If you want to generate a trigger when a button is on and another trigger (or the same trigger) when the button goes off you need to specify the triggerOn and triggerOff parameter.
