### ISSUE TITLE
Possible to use plugin to trigger an accessory?

### ISSUE THREAD

**Issue by hangmanandhide** [ilcato/homebridge-ifttt#35]
I am trying to figure out a workflow solution that will work that will allow me open and close my garage. Using the homebridge-liftmaster2 plugin I can effectively open and close the garage with siri, but for me to be able to do this with my google assistant/home hubs I will need to setup a virtual switch with Samsung's SmartThings hub. 

My hope is that I can use this homebridge-ifttt plugin to create an OpenGarage webhook and a CloseGarage webhook that I can then tie to the virtual switch.

Is there any chance there's a way to script the config of homebridge-ifttt to trigger an already existing accessory in the config.json?

**Comment by rgerr** [comment]
Of course, simply create an automation in which you state if accessory one is on, then turn on accessory two.
