### ISSUE TITLE
about the json

### ISSUE THREAD

**Issue by barack65** [ilcato/homebridge-ifttt#45]
"caption": "A1-1",
							"triggerOn": "T1-1On",
							"triggerOff": "T1-1Off",
							"delayOn": 4,
							"delayOff": 3,
							"stateful": true
						},

**what is the T1-1ON ?**

**Comment by ilcato** [comment]
@barack65, it is the event name sent to IFTTT in las of turning the button on in HomeKit.

**Comment by barack65** [comment]
Yes, but I stop use the ifttt platform

**Comment by ilcato** [comment]
ok, closing.
