### ISSUE TITLE
1.0.1 update bugs?

### ISSUE THREAD

**Issue by benmkoch** [ilcato/homebridge-ifttt#49]
Since I updated the plug-in my switches have disappeared. I didn't change the json code after updating (first 1.0.0 and now 1.0.1) and the switches worked fine previously. Is there something I'm missing? The accessories load (according to the log) when restarting Homebridge, but they don't appear on the accessories page or on my ios device. Thanks for your help! This plug in is great!

**Comment by ilcato** [comment]
@donavanbecker, can you look at it?

**Comment by ilcato** [comment]
@benmkoch, can you share your config?

**Comment by benmkoch** [comment]
Thanks for looking into this! Below is my IFTTT config. If you'd like the complete file, I can share that too.

    {
            "name": "IFTTT",
            "makerkey": "cvxE7mD0bv6NYlx5-UBCyi",
            "accessories": [
                {
                    "name": "Bedroom Ceiling Fan",
                    "buttons": [
                        {
                            "caption": "Ceiling Fan",
                            "triggerOn": "BedFanOn",
                            "triggerOff": "BedFanOff"
                        }
                    ]
                },
                {
                    "name": "Bedroom Ceiling Fan Speed",
                    "buttons": [
                        {
                            "caption": "Medium Speed",
                            "trigger": "BedFanMed"
                        },
                        {
                            "caption": "Low Speed",
                            "trigger": "BedFanLow"
                        }
                    ]
                },
                {
                    "name": "Washing Machine",
                    "buttons": [
                        {
                            "caption": "Washer Done",
                            "trigger": "HBNotification",
                            "values": {
                                "value1": "Washer Done"
                            }
                        }
                    ]
                },
                {
                    "name": "Eco Mode Alert",
                    "buttons": [
                        {
                            "caption": "Eco Mode Alert",
                            "trigger": "HBNotification",
                            "values": {
                                "value1": "Eco Mode On"
                            }
                        }
                    ]
                }
            ],
            "platform": "IFTTT"
        },

**Comment by benmkoch** [comment]
Thanks for looking into this! Below is my IFTT config.

    {
            "name": "IFTTT",
            "makerkey": "REDACTED",
            "accessories": [
                {
                    "name": "Bedroom Ceiling Fan",
                    "buttons": [
                        {
                            "caption": "Ceiling Fan",
                            "triggerOn": "BedFanOn",
                            "triggerOff": "BedFanOff"
                        }
                    ]
                },
                {
                    "name": "Bedroom Ceiling Fan Speed",
                    "buttons": [
                        {
                            "caption": "Medium Speed",
                            "trigger": "BedFanMed"
                        },
                        {
                            "caption": "Low Speed",
                            "trigger": "BedFanLow"
                        }
                    ]
                },
                {
                    "name": "Washing Machine",
                    "buttons": [
                        {
                            "caption": "Washer Done",
                            "trigger": "HBNotification",
                            "values": {
                                "value1": "Washer Done"
                            }
                        }
                    ]
                },
                {
                    "name": "Eco Mode Alert",
                    "buttons": [
                        {
                            "caption": "Eco Mode Alert",
                            "trigger": "HBNotification",
                            "values": {
                                "value1": "Eco Mode On"
                            }
                        }
                    ]
                }
            ],
            "platform": "IFTTT"
        },

**Comment by ilcato** [comment]
@benmkoch, it works for me with your config. Try to remove the accessories folder and restart homebridge.

**Comment by donavanbecker** [comment]
sorry @ilcato just got to this.

**Comment by benmkoch** [comment]
@ilcato @donavanbecker Homebridge just released a new update which I installed and seemed to have fixed the issue. Apologies for the unnecessary red flag. I appreciate your work!
