### ISSUE TITLE
Update 1.0.1 Issue

### ISSUE THREAD

**Issue by richsc** [ilcato/homebridge-ifttt#50]
After installing the latest update the triggerOff command no longer works.

When the accessory is turned on it works as normal, when it is subsequently turned off the triggerOn command is sent instead of the triggerOff command.

Reverting back to version 0.4.1 resolves the issue.

**Comment by ilcato** [comment]
@richsc, should be fixed in 1.0.2

**Comment by richsc** [comment]
Thanks for quick response.
