### ISSUE TITLE
Issues with triggering Siri

### ISSUE THREAD

**Issue by snehalnayan** [ilcato/homebridge-ifttt#6]
Hi,

I was successfully able to install homebridge.
I created a maker channel trigger on IFTTT.

I used insteon+ as an app to detect and connect home bridge successfully.
Using insteon+ I can easily trigger my IFTTT turn on and turn off events.
I can see it on my console logs as well.

But nothing works using SiRi.

Here is the set up.
I have tried all combinations Fragrance, Activate Fragrance but nothing works.
If I name the accessory to insteon+ it just opens the app, so that as well is not an option.

Any help is appreciated

{
  "bridge": {
    "name": "HomebridgeIFTTT",
    "username": "CC:........",
    "port": 51......,
    "pin": "031......."
  },

  "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

  "platforms": [
    {
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "My Key",
      "accessories": [{
        "name": "Fragrance",
        "buttons": [
          {
            "caption": "Fragrance",
            "triggerOn": "Activate Fragrance",
            "triggerOff": "Deactivate Fragrance"
          }
        ]
      }
      ]
    }
  ]
}

**Comment by ilcato** [comment]
What does Siri respond to "turn on Fragrance" ?

**Comment by snehalnayan** [comment]
Ok got it to work.

"name": "Fragrance",
        "buttons": [
          {
            "caption": "Fragrance",
            "triggerOn": "Fragrance On",
            "triggerOff": "Fragrance Off"
          },{

And now if I say Siri, turn fragrance on it works !!!
Thanks for the help and the so very helpful API.
