### ISSUE TITLE
Help with configuration file...

### ISSUE THREAD

**Issue by theboyk** [ilcato/homebridge-ifttt#7]
Just wondering if I could get a little assistance with the config to connect Homebridge to a couple of channels for controlling an alarm (setting it to ARM or DISARM). I have two IFTTT Channels, as follows:

Channel Name: ArmAlarm
Trigger: Receive a web request
Event Name: Arm_Alarm
URL: https://maker.ifttt.com/trigger/Arm_Alarm/with/key/xxx

Channel Name: DisarmAlarm
Trigger: Receive a web request
Event Name: Disarm_Alarm
URL: https://maker.ifttt.com/trigger/Disarm_Alarm/with/key/xxx

Posting the web requests (above) works fine. Now I just need to tie it into Homebridge. Is my config correct, or am I doing something wrong?

```
platform": "IFTTT",
"name": "IFTTT",
"makerkey": "PUT KEY OF YOUR MAKER CHANNEL HERE",
"accessories": [{
             "name": "My Alarm",
             "buttons": [
             {
             "caption": "Arm_Alarm",
             "triggerOn": "Arm_Alarm"
             },
             "caption": "Disarm_Alarm",
             "triggerOn": "Disarm_Alarm"
             }
]
```

So, my questions:
1. In the config file, what parameter relates back to the the EVENT in the Maker Channel URL that gets posted? For example, the web request is https://maker.ifttt.com/trigger/EVENT/with/key/xxx — is it the "caption" or "triggerOn" parameter that needs to match the EVENT name in the URL?
2. In the config file, what parameter relates back to how I use Siri to perform these actions?
3. What do I actually tell Siri to do to trigger these actions?

Any advice would be appreciated!

Thanks!

**Comment by ilcato** [comment]
I'm assuming you put your Maker key in "PUT KEY OF YOUR MAKER CHANNEL HERE".

1. the event name is mapped on the trigger parameter (use trigger and not triggerOn; triggerOn is used together with triggerOff in order to have a bistable switch and not a push button; but currently there's no way to keep the status)
2. caption. caption is also used in the UI of HomeKit apps.
3. turn on "caption"

**Comment by theboyk** [comment]
Yep, actual key is in the working code. :)

Re: Caption & "talking" to Siri. So, is there a set of commands you can speak? For example, saying "Siri, turn on Disarm Alarm" is kinda weird. Instead, Could I caption the disarm trigger something like "DISABLED MODE" (for the accessory MY ALARM) and then say something like "Siri, set MY ALARM to DISABLED MODE" or "Siri, activate DISABLED MODE on MY ALARM"?

Just trying to figure out the best way to set the caption so it makes a bit of sense when using Siri.

**Comment by ilcato** [comment]
You can define an HomeKit scene that activate the switch.

You can invoke a scene via Siri with "activate scene_name" or if the scene_name is not ambiguous or overlapped with other Siri commands simply by saying "scene_name".

**Comment by theboyk** [comment]
Thanks.

I have it working via the following code:

```
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "xyz",
      "accessories": [
        {
          "name": "Security System",
          "buttons": [
            {
              "caption": "armed",
              "trigger": "arm"
            },{
              "caption": "disarmed",
              "trigger": "disarm"
            },{
              "caption": "home",
              "trigger": "home"
            }
          ]
        }
      ]
```

But, still having issues with regards to issuing the commands via Siri. The only way I can get it to work is to say "Turn on armed" or "Turn on disarmed". I tried endless other combinations and nothing worked.

Once thing I did notice, though, is that in the iOS app ([Devices](https://itunes.apple.com/us/app/devices/id966877433?mt=8&ign-mpt=uo%3D4)) that I use to manage the HomeKit (Homebridge) devices that I've registered with the system, with my other devices (a Nest thermostat and WeMo smart plugs), all those devices show up as single accessories in the app (for example, a single Nest thermostat and a single WeMo smart plug for each one I have). But, with my IFTTT device, rather than showing up as single accessory ("Security System"), "Security System" doesn't show up at all. Instead, three accessories show up in the app—one per "button" (so, in the app, I have three new accessories—arm, disarm and home). Is this the correct behaviour?

Anyway, based on the above, would the following work?

```
      "platform": "IFTTT",
      "name": "IFTTT",
      "makerkey": "xyz",
      "accessories": [
        {
          "name": "Security System",
          "buttons": [
            {
              "caption": "Set the security system to armed",
              "trigger": "arm"
            },{
              "caption": "Set the security system to disarmed",
              "trigger": "disarm"
            },{
              "caption": "Set the security system to home mode",
              "trigger": "home"
            }
          ]
        }
      ]
```

Would I now be cause to say "Set the security system to armed" and have that work?

I realize I could build scenes (in the Devices iOS app I'm using) that activate the options (arm, disarm, home), but the problem with this is I have to set up these scenes, over and over again, for each iOS device I have. Or, is there a way to build scenes programmatically, that would work with all iOS devices on the LAN?

Thanks,
Kristin.

**Comment by ilcato** [comment]
HomeKit scenes are replicated automatically between iOs devices provided all devices are associated to the same iCloud account.

**Comment by theboyk** [comment]
Yeah, problem for me is, I gotta do this for the whole family, and each member has their own iCloud account (was hoping it would take into account Family Sharing, but doesn't seem to).

**Comment by ilcato** [comment]
what happens if you invite them through HomeKit setup panel for your home?

**Comment by theboyk** [comment]
Yep...had no clue that option existed until about 5 minutes ago, so that solves that problem. Thanks!

**Comment by cordell25** [comment]
I am having the same problems with the siri commands.  Have you figured out a good combination of names and verbiage to use?

**Comment by ilcato** [comment]
@cordell25, which problem?

**Comment by cordell25** [comment]
@ilcato 
In the config.json file you have a couple places you can make descriptions:
name: "myName" 
caption: "myCaption"

So what I'd like to understand is what are the Siri commands to allow me to reference the name and caption that I define to trigger this IFTTT recipe?

It would be nice to have a list of options that will work, filling in the blanks for the user defined name and caption.

**Comment by ilcato** [comment]
the "caption" value is the one that Siri recognize. So you can say something like "Turn on myCaption".
As I mention in the previous posts you can create HomeKit scenes that refer to the device and activate it by saying "Activate sceneName" provided sceneName is the name that you choose for the scene.

**Comment by cordell25** [comment]
I think maybe siri is getting confused when I use the name of the device I am controlling (Homeboy) which is also an app on my phone.  It may be trying to interact with the app instead of the homebridge command.

Forgetting about that issue, how would you suggest I setup the ability to "arm" and "disarm" my security camera (which is called a Homeboy).  I have setup two maker IFTTT recipes to trigger the arm / disarm, now I am wanting to setup this homebridge config in the most user friendly way.  Suggestions?

**Comment by ilcato** [comment]
The easiest way is to create scenes the call the IFTTT switches.

**Comment by DiMarcello77** [comment]
For me it works now with with homebridge / homekit & Siri (talking dutch to her ;-) with the following configuration for Arlo security camera's:

		{
			"platform": "IFTTT",
			"name": "IFTTT",
			"makerkey": "KEY,
			"accessories": [{
				"name": "Arlo",
				"buttons": [{
					"caption": "Camera",
					"triggerOn": "Arm",
					"triggerOff": "Disarm"
				}]
			}]
		}

The result is that I get one on / off switch for arming and disarming my camera system and saying the same "Arm Camera"
